# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: xarm7
  joint_model_group_pose: left_home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - L_joint1
    - L_joint2
    - L_joint3
    - L_joint4
    - L_joint5
    - L_joint6
    - R_joint1
    - R_joint2
    - R_joint3
    - R_joint4
    - R_joint5
    - R_joint6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []